### ISSUE TITLE
Add a job to automatically update nix flake

### ISSUE THREAD

**Issue by arthsmn** [hyprland-community/hyprls#15]
I'm not familiar with Github's workflows but it seems straightforward. Hyprland has it: https://github.com/hyprwm/Hyprland/blob/main/.github/workflows/nix-update-inputs.yml.

**Comment by ewen-lbh** [comment]
Seems good, except for the commit message (we're using the gitmoji standard) and the PAT secret (it seems unnecessary for cloning, i think we can just remove it)

Apart from that we might be able to just copy the file
