### ISSUE TITLE
Collision between `hyprls` and `golines`

### ISSUE THREAD

**Issue by Libadoxon** [hyprland-community/hyprls#19]
Both packages provide a binary named `generate`. This causes a collision when using `home-manager` on `NixOs`. I don't know what it does or if it needs to be in the users PATH, both for `hyprls` and `golines`. The name `generate` is also very generic so I think its likely that there will be more collisions in the future. So renaming it should be considered, I would say.

**Comment by ewen-lbh** [comment]
wooops yeah that's pretty cringe

the `go install` command installs it?

the binary is technically meant only for development anyway

**Comment by ewen-lbh** [comment]
(specifically, it's used to generate data from the wiki files, see

https://github.com/hyprland-community/hyprls/blob/101ed4e136441a985d2e562df8b3373cde46fe69/Justfile#L37-L45)

**Comment by Libadoxon** [comment]
so is there a way to disable the building of it? A flag or something?

**Comment by ewen-lbh** [comment]
well if you're building from source building that binary is necessary
the issue is more that it somehow adds itself to the PATH

**Comment by Libadoxon** [comment]
That's because nix thinks anything that is build should be be added the users path. The binary needs to be deleted in a phase/hook. I will open a pull request fixing this soon
