### ISSUE TITLE
[Feature Request] Publish VSCode extension to Open VSX

### ISSUE THREAD

**Issue by wathhr** [hyprland-community/hyprls#22]
As documented [here](https://github.com/VSCodium/vscodium/blob/master/docs/index.md#extensions--marketplace) VSCodium users are unable to install the hyprls extension via the normal VSCode marketplace, making this extension annoying to install.

VSCodium supports [Open VSX](https://open-vsx.org/) instead, so it would be very beneficial for the extension to be published there as well.

**Comment by ewen-lbh** [comment]
While we wait for EclipseFdn's response (idk how much time i should expect), I added the .vsix to [the latest github release](https://github.com/hyprland-community/hyprls/releases/tag/v0.2.0)
