### ISSUE TITLE
Simplify language server startup

### ISSUE THREAD

**Issue by Cloudperry** [hyprland-community/hyprls#9]
The readme suggests to use an autocmd for starting the language server. The LS can also be started by adding "hyprlang" to the filetypes option of the LS and running this: 

```lua
vim.filetype.add({
  pattern = { [".*/hypr/.*%.conf"] = "hyprlang" },
})
```

Maybe you should change the filetypes option to include "hyprlang" by default and suggest using this filetype detection pattern for starting the LS. The autocmd is a very non-standard way of starting it and in my Neovim it seemed to trigger very often (when going to command mode and back etc).

**Comment by ewen-lbh** [comment]
Will do! see #12
